- name: Mapper Reduccer Jobs
  copy:
    # src: /root/lab-hadoop/mapper-reducer-jobs
    # dest: /home/hadoop/
    content: "/root/lab-hadoop/mapper-reducer-jobs"
    dest: "/home/hadoop/"
    when: inventory_hostname = ip_master
    remote_src: yes
    recursive: yes
