# for local development
version: '3.7'
services:
  hadoop:
    build:
      context: .
      target: 'develop-stage'
    ports:
    - '3001:3000'
    volumes:
    - '../.:/lab-hadoop'
    working_dir: /lab-hadoop
    container_name: lab-hadoop
    environment:
    - GCP_SERVICE_ACCOUNT_FILE=./keyfile.json
    - GOOGLE_APPLICATION_CREDENTIALS=./keyfile.json
    command: bash -c "/bin/bash" # "terraform init && terraform plan && terraform apply && /bin/bash" # && if [ -d "./tmp/pids" ]; then rm -f ./tmp/pids/*; fi && service redis-server start && rails s -b 0.0.0.0 && /bin/bash"
    stdin_open: true
    tty: true
    networks:
      - default
networks:
  defualt:
    driver: bridge